"""add geocoding fields to delivery_points

Revision ID: bc9f7add114f
Revises: 1a2b3c4d5e6f
Create Date: 2026-03-03 16:54:22.635071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9f7add114f'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_points', sa.Column('geocode_status', sa.String(length=32), nullable=True))
    op.add_column('delivery_points', sa.Column('geocode_provider', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_delivery_points_geocode_provider'), 'delivery_points', ['geocode_provider'], unique=False)
    op.create_index(op.f('ix_delivery_points_geocode_status'), 'delivery_points', ['geocode_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_points_geocode_status'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_geocode_provider'), table_name='delivery_points')
    op.drop_column('delivery_points', 'geocode_provider')
    op.drop_column('delivery_points', 'geocode_status')
    # ### end Alembic commands ###
