"""add clients delivery_points many-to-many

Revision ID: e079c37a071a
Revises: 
Create Date: 2026-02-21 18:51:59.227133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e079c37a071a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_table('delivery_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('zip', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_points_address'), 'delivery_points', ['address'], unique=False)
    op.create_index(op.f('ix_delivery_points_city'), 'delivery_points', ['city'], unique=False)
    op.create_index(op.f('ix_delivery_points_country'), 'delivery_points', ['country'], unique=False)
    op.create_index(op.f('ix_delivery_points_name'), 'delivery_points', ['name'], unique=False)
    op.create_index(op.f('ix_delivery_points_state'), 'delivery_points', ['state'], unique=False)
    op.create_index(op.f('ix_delivery_points_zip'), 'delivery_points', ['zip'], unique=False)
    op.create_table('client_delivery_points',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('delivery_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_point_id'], ['delivery_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'delivery_point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_delivery_points')
    op.drop_index(op.f('ix_delivery_points_zip'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_state'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_name'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_country'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_city'), table_name='delivery_points')
    op.drop_index(op.f('ix_delivery_points_address'), table_name='delivery_points')
    op.drop_table('delivery_points')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
